In [1]:
import pandas as pd

# oth-regensburg-1_1_2022

In [11]:
data_archieve = pd.read_csv("oth-regensburg-1_1_2022/oth-regensburg-1.csv")
print(data_archieve.shape)
data_archieve.head()

/Users/ken/opt/anaconda3/envs/nilmtk-env/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3221: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

(2293528, 27)

,Id,Name,Serial,DeviceEnergyType,MeterSubType,ActivePower,CounterReading,CounterReadingT1,CounterReadingT2,CounterReadingExport,...,VoltageL3,Current,CurrentL1,CurrentL2,CurrentL3,PowerFactor,PowerFactorL1,PowerFactorL2,PowerFactorL3,DigitalInput1
0,43043308-a366-4af4-881c-6bae4a0a0dc3,smart-me 6011785 - Allgemein,6011785,MeterTypeElectricity,NaN,0.083220,1413.272491,1413.272491,0.0,3.630487,...,228.8,NaN,0.360,0.447,0.17,0.346,0.346,0.537,0.0,NaN
1,aa680cb9-5092-4483-84fe-a5df826a55c4,smart-me 6011209 Batterie,6011209,MeterTypeElectricity,NaN,-0.018130,-634.755910,-634.755910,0.0,4477.415412,...,0.0,NaN,-0.183,0.000,0.00,0.434,0.434,0.000,0.0,NaN
2,2c6913bf-c807-4592-a148-a891b6174aae,Gesamtverbrauch,637686123692284276,13,MeterSubTypeElectricity,0.894020,37328.466621,37328.466621,0.0,3.630489,...,NaN,0.0,0.000,0.000,0.00,NaN,NaN,NaN,NaN,NaN
3,53ad1504-0a3d-4074-b848-c4eb46367bab,Virtueller Produktionszähler,637686127388299418,13,MeterSubTypeElectricity,-0.622640,-15740.204340,-15740.204340,0.0,19687.472960,...,NaN,0.0,0.000,0.000,0.00,NaN,NaN,NaN,NaN,NaN
4,e8755559-b3da-4a71-baa6-109fd1304248,smart-me 6011227 - Heizung,6011227,MeterTypeElectricity,NaN,0.069033,21436.311855,21436.311855,0.0,0.000000,...,229.0,NaN,0.433,0.000,0.00,0.704,0.704,0.000,0.0,NaN

In [12]:
data_archieve.Name.unique()

array(['smart-me 6011785 - Allgemein', 'smart-me 6011209 Batterie',
       'Gesamtverbrauch', 'Virtueller Produktionszähler',
       'smart-me 6011227 - Heizung', 'smart-me 6011505 - Wohnung 1',
       'smart-me 6011754 - Wohnung 2', 'smart-me 6011232 - Wohnung 3',
       'smart-me 6011231 - Wohnung 4', 'smart-me 6011210 - Wohnung 5',
       'smart-me 6011243 - Wohnung 6', 'smart-me 6011242 - Wohnung 7',
       'NewDevice'], dtype=object)

In [13]:
data_archieve.ValueDate.unique()

array(['01/03/2022 13:40:01', '01/03/2022 13:39:49',
       '01/03/2022 13:39:58', ..., '01/31/2022 22:59:57',
       '01/31/2022 23:00:20', '01/31/2022 23:00:21'], dtype=object)

In [4]:
data_archieve_1 = pd.read_csv("oth-regensburg-1_1_2022/oth-regensburg-1(1).csv")
print(data_archieve_1.shape)
data_archieve_1.head()

(11, 27)

,Id,Name,Serial,DeviceEnergyType,MeterSubType,ActivePower,CounterReading,CounterReadingT1,CounterReadingT2,CounterReadingExport,...,VoltageL3,Current,CurrentL1,CurrentL2,CurrentL3,PowerFactor,PowerFactorL1,PowerFactorL2,PowerFactorL3,DigitalInput1
0,43043308-a366-4af4-881c-6bae4a0a0dc3,smart-me 6011785 - Allgemein,6011785,MeterTypeElectricity,NaN,0.134519,1501.285658,1501.285658,0.0,3.781994,...,228.4,NaN,0.357,0.631,0.173,0.353,0.353,0.696,0.153,NaN
1,aa680cb9-5092-4483-84fe-a5df826a55c4,smart-me 6011209 Batterie,6011209,MeterTypeElectricity,NaN,-0.008650,-652.061632,-652.061632,0.0,4524.506797,...,0.0,NaN,-0.057,0.000,0.000,0.657,0.657,0.000,0.000,NaN
2,e8755559-b3da-4a71-baa6-109fd1304248,smart-me 6011227 - Heizung,6011227,MeterTypeElectricity,NaN,4.489816,22903.766731,22903.766731,0.0,0.000000,...,228.4,NaN,9.307,7.677,7.605,0.871,0.871,0.772,0.759,NaN
3,a9dad66e-8a0b-457f-8cd8-644aeddee557,smart-me 6011505 - Wohnung 1,6011505,MeterTypeElectricity,NaN,0.127648,2093.418476,2093.418476,0.0,0.000000,...,228.4,NaN,0.689,0.503,0.250,0.096,0.096,0.509,0.950,NaN
4,1731e782-145c-4317-8291-f875746fdcc8,smart-me 6011754 - Wohnung 2,6011754,MeterTypeElectricity,NaN,0.453983,3173.136103,3173.136103,0.0,0.000000,...,228.5,NaN,0.537,1.552,0.157,0.682,0.682,0.995,0.520,NaN

In [5]:
data_archieve_2 = pd.read_csv("oth-regensburg-1_1_2022/oth-regensburg-1(2).csv")
print(data_archieve_2.shape)
data_archieve_2.head()

(11, 27)

,Id,Name,Serial,DeviceEnergyType,MeterSubType,ActivePower,CounterReading,CounterReadingT1,CounterReadingT2,CounterReadingExport,...,VoltageL3,Current,CurrentL1,CurrentL2,CurrentL3,PowerFactor,PowerFactorL1,PowerFactorL2,PowerFactorL3,DigitalInput1
0,43043308-a366-4af4-881c-6bae4a0a0dc3,smart-me 6011785 - Allgemein,6011785,MeterTypeElectricity,NaN,0.137462,1501.285771,1501.285771,0.0,3.781994,...,228.4,NaN,0.357,0.640,0.173,0.353,0.353,0.705,0.153,NaN
1,aa680cb9-5092-4483-84fe-a5df826a55c4,smart-me 6011209 Batterie,6011209,MeterTypeElectricity,NaN,-0.008650,-652.061632,-652.061632,0.0,4524.506797,...,0.0,NaN,-0.057,0.000,0.000,0.657,0.657,0.000,0.000,NaN
2,e8755559-b3da-4a71-baa6-109fd1304248,smart-me 6011227 - Heizung,6011227,MeterTypeElectricity,NaN,4.489316,22903.769226,22903.769226,0.0,0.000000,...,228.4,NaN,9.305,7.678,7.605,0.871,0.871,0.771,0.759,NaN
3,a9dad66e-8a0b-457f-8cd8-644aeddee557,smart-me 6011505 - Wohnung 1,6011505,MeterTypeElectricity,NaN,0.127595,2093.418547,2093.418547,0.0,0.000000,...,228.4,NaN,0.689,0.502,0.251,0.096,0.096,0.509,0.950,NaN
4,1731e782-145c-4317-8291-f875746fdcc8,smart-me 6011754 - Wohnung 2,6011754,MeterTypeElectricity,NaN,0.407368,3173.136468,3173.136468,0.0,0.000000,...,228.5,NaN,0.531,1.409,0.158,0.679,0.679,0.954,0.521,NaN

# oth-regensburg-1

In [2]:
data = pd.read_csv("oth-regensburg-1/oth-regensburg-1.csv")
print(data.shape)
data.head()

(1550472, 27)

,Id,Name,Serial,DeviceEnergyType,MeterSubType,ActivePower,CounterReading,CounterReadingT1,CounterReadingT2,CounterReadingExport,...,VoltageL3,Current,CurrentL1,CurrentL2,CurrentL3,PowerFactor,PowerFactorL1,PowerFactorL2,PowerFactorL3,DigitalInput1
0,43043308-a366-4af4-881c-6bae4a0a0dc3,smart-me 6011785 - Allgemein,6011785,MeterTypeElectricity,NaN,0.133324,3016.232117,3016.232117,0.0,7.343095,...,234.6,NaN,0.361,0.614,0.172,0.333,0.333,0.690,0.152,NaN
1,aa680cb9-5092-4483-84fe-a5df826a55c4,smart-me 6011209 Batterie,6011209,MeterTypeElectricity,NaN,-0.008716,-1761.777895,-1761.777895,0.0,12496.138372,...,0.0,NaN,-0.057,0.000,0.000,0.650,0.650,0.000,0.000,NaN
2,2c6913bf-c807-4592-a148-a891b6174aae,Gesamtverbrauch,637686123692284276,13,MeterSubTypeElectricity,0.750239,75000.402125,75000.402125,0.0,7.343097,...,NaN,0.0,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN
3,e8755559-b3da-4a71-baa6-109fd1304248,smart-me 6011227 - Heizung,6011227,MeterTypeElectricity,NaN,0.047855,36439.485954,36439.485954,0.0,0.000000,...,234.6,NaN,0.321,0.000,0.000,0.642,0.642,0.000,0.000,NaN
4,a9dad66e-8a0b-457f-8cd8-644aeddee557,smart-me 6011505 - Wohnung 1,6011505,MeterTypeElectricity,NaN,0.052729,4050.142234,4050.142234,0.0,0.000000,...,234.6,NaN,0.701,0.467,0.091,0.054,0.054,0.402,0.000,NaN

In [5]:
data.Name.unique()

array(['smart-me 6011785 - Allgemein', 'smart-me 6011209 Batterie',
       'Gesamtverbrauch', 'smart-me 6011227 - Heizung',
       'smart-me 6011505 - Wohnung 1', 'smart-me 6011754 - Wohnung 2',
       'smart-me 6011232 - Wohnung 3', 'smart-me 6011231 - Wohnung 4',
       'smart-me 6011210 - Wohnung 5', 'smart-me 6011243 - Wohnung 6',
       'smart-me 6011242 - Wohnung 7', 'NewDevice'], dtype=object)

# Wohnung 1

In [10]:
data[data.Name.str.contains("Wohnung 1")].shape

(129206, 27)

In [6]:
data[data.Name.str.contains("Wohnung 1")].head()

,Id,Name,Serial,DeviceEnergyType,MeterSubType,ActivePower,CounterReading,CounterReadingT1,CounterReadingT2,CounterReadingExport,...,VoltageL3,Current,CurrentL1,CurrentL2,CurrentL3,PowerFactor,PowerFactorL1,PowerFactorL2,PowerFactorL3,DigitalInput1
4,a9dad66e-8a0b-457f-8cd8-644aeddee557,smart-me 6011505 - Wohnung 1,6011505,MeterTypeElectricity,NaN,0.052729,4050.142234,4050.142234,0.0,0.0,...,234.6,NaN,0.701,0.467,0.091,0.054,0.054,0.402,0.0,NaN
16,a9dad66e-8a0b-457f-8cd8-644aeddee557,smart-me 6011505 - Wohnung 1,6011505,MeterTypeElectricity,NaN,0.053102,4050.142263,4050.142263,0.0,0.0,...,234.6,NaN,0.701,0.469,0.091,0.054,0.054,0.405,0.0,NaN
28,a9dad66e-8a0b-457f-8cd8-644aeddee557,smart-me 6011505 - Wohnung 1,6011505,MeterTypeElectricity,NaN,0.052937,4050.142293,4050.142293,0.0,0.0,...,234.6,NaN,0.701,0.468,0.091,0.054,0.054,0.405,0.0,NaN
40,a9dad66e-8a0b-457f-8cd8-644aeddee557,smart-me 6011505 - Wohnung 1,6011505,MeterTypeElectricity,NaN,0.052926,4050.142322,4050.142322,0.0,0.0,...,234.5,NaN,0.701,0.468,0.091,0.054,0.054,0.404,0.0,NaN
52,a9dad66e-8a0b-457f-8cd8-644aeddee557,smart-me 6011505 - Wohnung 1,6011505,MeterTypeElectricity,NaN,0.053356,4050.142337,4050.142337,0.0,0.0,...,234.6,NaN,0.701,0.469,0.091,0.055,0.055,0.406,0.0,NaN

In [10]:
wohnung_1 = pd.read_csv("Wohnung1.csv")
wohnung_1.head()

   Unnamed: 0  ActivePower                  ValueDate
0           0       52.729  2023-08-01 00:00:03+02:00
1           1       53.102  2023-08-01 00:00:05+02:00
2           2       52.937  2023-08-01 00:00:07+02:00
3           3       52.926  2023-08-01 00:00:09+02:00
4           4       53.356  2023-08-01 00:00:10+02:00

In [14]:
wohnung_1.shape

(4202, 11)